[package]
name = "zhongwen-anki"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]
edition = "2018"

description = "Tool to create Anki decks for learning Chinese"
homepage = "https://github.com/arminha/zhongwen-anki"
repository = "https://github.com/arminha/zhongwen-anki"

readme = "README.md"
license = "GPL-3.0"

[profile.release]
lto = true

[dependencies]
unicode-segmentation = "1.6.0"
lazy_static = "1.4.0"
csv = "1.1.3"
serde = { version = "1.0.104", features = ["derive"] }
structopt = "0.3.9"
