[package]
name = "zhongwen-anki"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]

[profile.release]
lto = true

[dependencies]
unicode-segmentation = "1.2.1"
lazy_static = "1.2.0"
csv = "1.0.1"
serde_derive = "1.0.78"
structopt = "0.2.10"
serde = "1.0.78"
